steps:
  - name: 'gcr.io/$PROJECT_ID/packer'
    args:
      - init
      - .
  - name: 'gcr.io/$PROJECT_ID/packer'
    env:
      - 'PKR_VAR_zone=$_PKR_VAR_ZONE'
      - 'PKR_VAR_project_id=$_PKR_VAR_PROJECT_ID'
      - 'PKR_VAR_subnet=$_PKR_VAR_SUBNET'
      - 'PKR_VAR_service_account_email=$_PKR_VAR_SERVICE_ACCOUNT_EMAIL'
    args:
      - build
      - .